/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as UsernameFolderRouteImport } from './routes/$username.$folder'
import { Route as AppContaRouteImport } from './routes/app/conta'
import { Route as AppLinktreeRouteImport } from './routes/app/linktree'
import { Route as AppLinktreeIndexRouteImport } from './routes/app/linktree/index'
import { Route as AppLinktreeFolderRouteImport } from './routes/app/linktree/folder'
import { Route as AppLinktreeLinksRouteImport } from './routes/app/linktree/links'
import { Route as AppLinktreePageRouteImport } from './routes/app/linktree/page'
import { Route as AppLinktreeStatsRouteImport } from './routes/app/linktree/stats'
import { Route as AppLinktreeThemesRouteImport } from './routes/app/linktree/themes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameFolderRoute = UsernameFolderRouteImport.update({
  id: '/$folder',
  path: '/$folder',
  getParentRoute: () => UsernameRoute,
} as any)
const AppContaRoute = AppContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AppRoute,
} as any)
const AppLinktreeRoute = AppLinktreeRouteImport.update({
  id: '/linktree',
  path: '/linktree',
  getParentRoute: () => AppRoute,
} as any)
const AppLinktreeIndexRoute = AppLinktreeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLinktreeRoute,
} as any)
const AppLinktreeFolderRoute = AppLinktreeFolderRouteImport.update({
  id: '/folder',
  path: '/folder',
  getParentRoute: () => AppLinktreeRoute,
} as any)
const AppLinktreeLinksRoute = AppLinktreeLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AppLinktreeRoute,
} as any)
const AppLinktreePageRoute = AppLinktreePageRouteImport.update({
  id: '/page',
  path: '/page',
  getParentRoute: () => AppLinktreeRoute,
} as any)
const AppLinktreeStatsRoute = AppLinktreeStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppLinktreeRoute,
} as any)
const AppLinktreeThemesRoute = AppLinktreeThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AppLinktreeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/$username/$folder': typeof UsernameFolderRoute
  '/app/conta': typeof AppContaRoute
  '/app/linktree': typeof AppLinktreeRouteWithChildren
  '/app/linktree/folder': typeof AppLinktreeFolderRoute
  '/app/linktree/links': typeof AppLinktreeLinksRoute
  '/app/linktree/page': typeof AppLinktreePageRoute
  '/app/linktree/stats': typeof AppLinktreeStatsRoute
  '/app/linktree/themes': typeof AppLinktreeThemesRoute
  '/app/linktree/': typeof AppLinktreeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/$username/$folder': typeof UsernameFolderRoute
  '/app/conta': typeof AppContaRoute
  '/app/linktree/folder': typeof AppLinktreeFolderRoute
  '/app/linktree/links': typeof AppLinktreeLinksRoute
  '/app/linktree/page': typeof AppLinktreePageRoute
  '/app/linktree/stats': typeof AppLinktreeStatsRoute
  '/app/linktree/themes': typeof AppLinktreeThemesRoute
  '/app/linktree': typeof AppLinktreeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/$username/$folder': typeof UsernameFolderRoute
  '/app/conta': typeof AppContaRoute
  '/app/linktree': typeof AppLinktreeRouteWithChildren
  '/app/linktree/folder': typeof AppLinktreeFolderRoute
  '/app/linktree/links': typeof AppLinktreeLinksRoute
  '/app/linktree/page': typeof AppLinktreePageRoute
  '/app/linktree/stats': typeof AppLinktreeStatsRoute
  '/app/linktree/themes': typeof AppLinktreeThemesRoute
  '/app/linktree/': typeof AppLinktreeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/$username/$folder'
    | '/app/conta'
    | '/app/linktree'
    | '/app/linktree/folder'
    | '/app/linktree/links'
    | '/app/linktree/page'
    | '/app/linktree/stats'
    | '/app/linktree/themes'
    | '/app/linktree/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/$username/$folder'
    | '/app/conta'
    | '/app/linktree/folder'
    | '/app/linktree/links'
    | '/app/linktree/page'
    | '/app/linktree/stats'
    | '/app/linktree/themes'
    | '/app/linktree'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/$username/$folder'
    | '/app/conta'
    | '/app/linktree'
    | '/app/linktree/folder'
    | '/app/linktree/links'
    | '/app/linktree/page'
    | '/app/linktree/stats'
    | '/app/linktree/themes'
    | '/app/linktree/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/$folder': {
      id: '/$username/$folder'
      path: '/$folder'
      fullPath: '/$username/$folder'
      preLoaderRoute: typeof UsernameFolderRouteImport
      parentRoute: typeof UsernameRoute
    }
    '/app/conta': {
      id: '/app/conta'
      path: '/conta'
      fullPath: '/app/conta'
      preLoaderRoute: typeof AppContaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/linktree': {
      id: '/app/linktree'
      path: '/linktree'
      fullPath: '/app/linktree'
      preLoaderRoute: typeof AppLinktreeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/linktree/': {
      id: '/app/linktree/'
      path: '/'
      fullPath: '/app/linktree/'
      preLoaderRoute: typeof AppLinktreeIndexRouteImport
      parentRoute: typeof AppLinktreeRoute
    }
    '/app/linktree/folder': {
      id: '/app/linktree/folder'
      path: '/folder'
      fullPath: '/app/linktree/folder'
      preLoaderRoute: typeof AppLinktreeFolderRouteImport
      parentRoute: typeof AppLinktreeRoute
    }
    '/app/linktree/links': {
      id: '/app/linktree/links'
      path: '/links'
      fullPath: '/app/linktree/links'
      preLoaderRoute: typeof AppLinktreeLinksRouteImport
      parentRoute: typeof AppLinktreeRoute
    }
    '/app/linktree/page': {
      id: '/app/linktree/page'
      path: '/page'
      fullPath: '/app/linktree/page'
      preLoaderRoute: typeof AppLinktreePageRouteImport
      parentRoute: typeof AppLinktreeRoute
    }
    '/app/linktree/stats': {
      id: '/app/linktree/stats'
      path: '/stats'
      fullPath: '/app/linktree/stats'
      preLoaderRoute: typeof AppLinktreeStatsRouteImport
      parentRoute: typeof AppLinktreeRoute
    }
    '/app/linktree/themes': {
      id: '/app/linktree/themes'
      path: '/themes'
      fullPath: '/app/linktree/themes'
      preLoaderRoute: typeof AppLinktreeThemesRouteImport
      parentRoute: typeof AppLinktreeRoute
    }
  }
}

interface UsernameRouteChildren {
  UsernameFolderRoute: typeof UsernameFolderRoute
}

const UsernameRouteChildren: UsernameRouteChildren = {
  UsernameFolderRoute: UsernameFolderRoute,
}

const UsernameRouteWithChildren = UsernameRoute._addFileChildren(
  UsernameRouteChildren,
)

interface AppLinktreeRouteChildren {
  AppLinktreeFolderRoute: typeof AppLinktreeFolderRoute
  AppLinktreeLinksRoute: typeof AppLinktreeLinksRoute
  AppLinktreePageRoute: typeof AppLinktreePageRoute
  AppLinktreeStatsRoute: typeof AppLinktreeStatsRoute
  AppLinktreeThemesRoute: typeof AppLinktreeThemesRoute
  AppLinktreeIndexRoute: typeof AppLinktreeIndexRoute
}

const AppLinktreeRouteChildren: AppLinktreeRouteChildren = {
  AppLinktreeFolderRoute: AppLinktreeFolderRoute,
  AppLinktreeLinksRoute: AppLinktreeLinksRoute,
  AppLinktreePageRoute: AppLinktreePageRoute,
  AppLinktreeStatsRoute: AppLinktreeStatsRoute,
  AppLinktreeThemesRoute: AppLinktreeThemesRoute,
  AppLinktreeIndexRoute: AppLinktreeIndexRoute,
}

const AppLinktreeRouteWithChildren = AppLinktreeRoute._addFileChildren(
  AppLinktreeRouteChildren,
)

interface AppRouteChildren {
  AppContaRoute: typeof AppContaRoute
  AppLinktreeRoute: typeof AppLinktreeRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppContaRoute: AppContaRoute,
  AppLinktreeRoute: AppLinktreeRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
